### ISSUE TITLE
January Newsletter

### ISSUE THREAD

**Issue by ahdinosaur** [sunrise-choir/meta#1]
- Due 1 Feb
- Things to talk about
  - Lessbot + sqlclient
  - Pictures from arthack and holidays
  - Alj
  - Upcoming work
  - How others could contribute
    - funding
    - website / community building work

**Comment by pietgeursen** [comment]
- links to previous meeting notes

**Comment by pietgeursen** [comment]
- scuttlecamp / newsletter comms:
    - 3 project focuses to communicate:
        1. rusty sql flumeview: how we are enabling core queries to be done better
        2. consensus-free scuttlestack: how to run multiple clients, each with their own plugins & flumeviews without any possible conflicts
        3. born-again Scuttlebutt: how to evolve the Scuttlebutt project for the next generation of contributors
    - format: present these concepts, don't even need a working demo

- mik: the next newsletter can just be the story so far. 
  - work so far, directly quoting dev diaries:
      - mik's original post to introduce the project, context on why this project was created
      - pie's rusty bindings, private box 
      - alj's spec work (quote his ending post)
      - pie's rusty flume & sql flumeview
      - teasers of the upcoming work, mat joining
  - images
      - snapshot of mik's original post
      - snapshot of alj's spec website
      - all the messy whiteboard photos
      - pie's sql schema

**Comment by pietgeursen** [comment]
- mik: write newletter as .md file in https://github.com/sunrise-choir/meta in `newsletters/` as `2019-01.md`, put images in `newsletters/images/`
 - also post on medium
 - also post to the butts.

**Comment by ahdinosaur** [comment]
- also post on our new OpenCollective: https://opencollective.com/sunrise-choir

**Comment by ahdinosaur** [comment]
- also post on Twitter: https://twitter.com/sunrise_choir
